---
title: "Student Performance | GROUP I"
format: pdf
---

## Team

List the members of your team here: - Andrew Henderson - Carlos Mabrey - Seth Hillis - Jessica Reyes

## Data Set

"Students-scores.csv"

## Research Questions

1.  What are the effects of absence_days, extracurricular_activities, parent education and stress level have on student performance.

2.  Is there a relationship between career_aspiration and academic performance?

3.  How does the inclusion of part_time_job impact total score among students?

4.  How large is the effect of weekly_self_study_hours on a students average grade?

## Data Processing and Preparation

We will use 'part_time_job', 'absence_days', 'extracurricular_activities', 'weekly_self_study_hours', career_aspiration', and 'average_score'.
Make a few exploritory data analysis figures or tables to show the data you will use.

### Outcome(s)

-   average_score (from cleaning data and taking the average of each students scores per subject.)

### Predictors

Our predictor variables are 'part_time_job', 'absence_days', 'extracurricular_activities', 'weekly_self_study_hours', career_aspiration'
How will they be included in the model? For example, are they random effects? Will any be nonlinear? Will you include interaction terms? Are they continuous or categorical and how will you handle cateogrical variables?

### Subsample

Will you use all observations on only a subset of observations? If a subset, how will you select them and why?

### Other

There were no missing values in the data and the scores for each subject were condensed into an average score for each student.

Are any variables skewed or have outliers that are of concern? If so, how will you handle this?

## Modeling Approach

What model(s) do you propose to use? You may want to specify the model as a hierarchical model.

We think the block Gibbs Sampler and the rstanarm model, the traceplots showed convergence for all parameters, and the posterior predictive checks indicated that the model fit the data well.

$Y_i|\beta_0 \beta_1, \beta_2, \beta_3, \beta_4, \sigma^2  \sim N(\beta_0+ \beta_1 x_{1i}+ \beta_2 x_{2i}+ \beta_3 x_{3i}+ \beta_4 x_{4i},\sigma^2)$

where: $x_{1i},x_{2i},x_{3i},x_{4i}$ are the predictors for observation $i$.
$\sigma^2$ is the residual variance

$\beta_j \sim N(0, 10000^2)$ for all $j=0,1,2,3,4$

$\sigma^2 \sim InvGamma(1, 1)$

We considered including career aspirations as a predictor but decided not to incorporate it in this model, either because it was difficult to quantify appropriately.

How will you estimate your model?

We estimated the model using Bayesian sampling methods: Block Gibbs Sampling and rstanarm.
